### ISSUE TITLE
Parse Credit Card Statements

### ISSUE THREAD

**Issue by TechnicalJohn** [jcoliz/OFXSharp#16]
Currently, the code is looking for "BANKMSGSRSV1" and getting the statements from that. But in the DTD it defines several:

- BANKMSGSRSV1
- CREDITCARDMSGSRSV1
- WIREXFERMSGSRSV1
- INTERXFERMSGSRSV1
- INTERXFERMSGSRSV2

My pressing interest is having the ability to get Credit Card statements to work, but I'm wanting to check to see if you have an idea on how to do this in a thoughtful and efficient way. Suggestions?

Right now I'm working to expand the capabilities of FromXmlElement() and GetStatements() to accept and parse either "BANKMSGSRSV1" or "CREDITCARDMSGSRSV1".

**Comment by jcoliz** [comment]
Thanks. That's probably a good way to do it. I do have a more massive refactoring in mind that would also allow investment statements. But the way you described seems like the simplest.

**Comment by jcoliz** [comment]
Also, I suggest to start by creating a sample file which has example data representing what you want to parse. Add that to the tests. Add a failing test, then just mark it "explicit" so the automated tests won't pick it up.

**Comment by jcoliz** [comment]
I'm renaming this issue to focus on only the current work in view: Adding credit card statements. We can open new issues to cover other specific message sets.
