### ISSUE TITLE
Suggestion for using with Strongly Named assembly?

### ISSUE THREAD

**Issue by TechnicalJohn** [jcoliz/OFXSharp#5]
I have a project where I'm needing to use this but it's complaining that the dll is not strongly named. I've cloned this repo and added an SNK and compiled and that "fixes" the issue. 

So, can you add that to this assembly, or is that something I should do on my own... or do you have another suggestion?

**Comment by jcoliz** [comment]
Hi, @TechnicalJohn, thanks for looking into this. You can submit a pull request for this. Be sure to add the SNK file.

**Comment by jcoliz** [comment]
@TechnicalJohn I have added strong name signing, and released as version 3.1.0-rc1. Could you please try this out and see if it behaves as you expect?

https://www.nuget.org/packages/jcoliz.OfxSharp.NetStandard/3.1.0-rc1

**Comment by TechnicalJohn** [comment]
My apologies for the lack of response!

I just cloned and built this and it works exactly as expected! 

I'm interested to try it through NuGet as well to verify that it works through that way as well.

> @TechnicalJohn I have added strong name signing, and released as version 3.1.0-rc1. Could you please try this out and see if it behaves as you expect?
> 
> https://www.nuget.org/packages/jcoliz.OfxSharp.NetStandard/3.1.0-rc1

**Comment by jcoliz** [comment]
@TechnicalJohn, thanks so much for confirming. I have other projects asking for this too, so I wanted to experiment here first as a model for the others.

**Comment by TechnicalJohn** [comment]
@jcoliz, cool glad I could help!
