### ISSUE TITLE
Did we lose the ability to read OFX 2.0 XML?

### ISSUE THREAD

**Issue by TechnicalJohn** [jcoliz/OFXSharp#6]
Hello again!

It seems that this fork of OFXSharp can not parse an OFX 2.0 file (which is straight XML). But if I try out the original library by jhollingworth then there is no issue parsing an OFX 2.0 type file (although OFX 1.0 fails)... Am I missing something? 

Here is a sample of an OFX 2.0 file, which is XML and not SGML, and lacks the header region. This type of file covers qfx and qbo types that can be downloaded from many banks that don't offer "ofx":
[checking.qfx.txt](https://github.com/jcoliz/OFXSharp/files/9332166/checking.qfx.txt)
**NOTE:** I applied XML Pretty Printing to this example file so it would easier to grok, but the original was only one line and no line breaks.

LOL, the funny thing is that the jhollingworth version of OFXSharp **can not** parse the OFX 1.0 files that this current version has no issues parsing. So, if I'm not missing anything, it would seem we need to put in a check to see if it's a 1.0 (I think the header gives it away) or 2.0 type file, then parse accordingly?

**Comment by jcoliz** [comment]
Hi, thanks for digging into this. Sorry, I am away from the computer for another week, but I will look at this right away when I return!
